### PR TITLE
deps

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

- update dependencies

- add .nvmrc

- cleanup README

- bump version

### CODE REVIEW

**Comment by mattiaerre** [comment]
@fvictorio I think we can merge this one and publish a new version (the 0.0.4 is the current one in npm) so that we will get also the README there: https://www.npmjs.com/package/solidity-comments-extractor let me know what you think

**Review by fvictorio — APPROVED** [review]

**Comment by fvictorio** [comment]
Sure :+1:

**Comment by mattiaerre** [comment]
this has been merged, let me know when you publish the module so that I can update the dependency in the prettier plugin

**Comment by fvictorio** [comment]
Published! I also added you as an owner of the package in npm.

**Comment by mattiaerre** [comment]
thanks @fvictorio

**Pull request merged**
