### PR TITLE
documentation

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

- add documentation

- update .gitignore

- better prettier

- add eslint

### CODE REVIEW

**Comment by mattiaerre** [comment]
let me know if you want me to bump the version as well @fvictorio

**Comment by fvictorio** [comment]
I have one extra fix, let's do a beta after that

**Comment by mattiaerre** [comment]
I've also added eslint support btw

**Comment by fvictorio** [comment]
Oh, I read this notification in my phone and didn't notice it was this package :sweat_smile:

I don't think we need to release a new version since there's no functionality change. Publishing it would show the readme in npm though, so maybe that's why you want to do it? I'm ok with either option anyway.

**Pull request merged**
